workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Build and Sign iOS App
        script: |
          # 1. Setup the API Key file
          if [ -z "$PRIVATE_KEY" ]; then
            echo "ERROR: PRIVATE_KEY variable is missing."
            exit 1
          fi

          # Save key to a reliable local directory
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8

          # 2. Use Codemagic CLI to fetch/generate everything automatically
          # This handles certificates, keys, and profiles in one command
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          
          # 3. Build using the profiles fetched in step 2
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$ISSUER_ID" \
            -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8 \
            -allowProvisioningUpdates \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
    artifacts:
      - build/ios/xcarchive/*.xcarchive