workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Decode API Key and Setup Signing
        script: |
          # 1. Verification Step (Updated to match your screenshot names)
          # We check for PRIVATE_KEY first, then the longer name as fallback
          AUTH_KEY_DATA="${PRIVATE_KEY:-$APP_STORE_CONNECT_PRIVATE_KEY}"
          
          if [ -z "$AUTH_KEY_DATA" ]; then
            echo "CRITICAL ERROR: PRIVATE_KEY is not defined in Codemagic."
            echo "Your screenshot shows the variable name is 'PRIVATE_KEY'. Ensure it is in the 'apple_auth' group."
            exit 1
          fi

          # 2. Python Binary Writer
          python3 <<'EOF'
          import os
          import base64
          import sys

          # Match the variable name from your screenshot
          b64_data = (os.environ.get('PRIVATE_KEY') or os.environ.get('APP_STORE_CONNECT_PRIVATE_KEY') or '').strip()
          
          try:
              clean_b64 = "".join(b64_data.split())
              decoded = base64.b64decode(clean_b64)
              
              with open('/tmp/Apple_API_Key.p8', 'wb') as f:
                  f.write(decoded)
              print("SUCCESS: API Key decoded to /tmp/Apple_API_Key.p8")
          except Exception as e:
              print(f"ERROR: Base64 decoding failed: {e}")
              sys.exit(1)
          EOF

          chmod 600 /tmp/Apple_API_Key.p8
          
          # 3. Fetch Profiles
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 4. Identify Profile
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}" | head -n 1)
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 5. Create ExportOptions.plist
          cat <<EOF > /tmp/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROV_PROFILE_UUID</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF
      - name: Build iOS App
        script: |
          if [ ! -f /tmp/Apple_API_Key.p8 ]; then
            echo "Error: /tmp/Apple_API_Key.p8 was not created."
            exit 1
          fi
          
          # Use ISSUER_ID from your screenshot, fallback to long name
          FINAL_ISSUER_ID="${ISSUER_ID:-$APP_STORE_CONNECT_ISSUER_ID}"
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$FINAL_ISSUER_ID" \
            -authenticationKeyPath "/tmp/Apple_API_Key.p8" \
            -exportOptionsPlist /tmp/exportOptions.plist \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
    artifacts:
      - build/ios/xcarchive/*.xcarchive