workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.milltech.nurmecca.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa