workflows:
  ios-workflow:
    name: Nur-Mecca iOS Manual Build
    max_build_duration: 60
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC" 
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Set up code signing
        script: |
          # 1. Initialize the keychain
          keychain initialize
          
          # 2. Search everywhere for the uploaded .p12 file
          keychain add-certificates --global-keystore
          
          # 3. Use profiles without the unrecognized team-id flag
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          # Injecting the Team ID and Manual style directly into the xcodebuild command
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            clean archive
    artifacts:
      - build/ios/xcarchive/*.xcarchive