# PROJECT NUR-MECCA | Hybrid Automatic-to-Manual Signing
workflows:
  ios-production:
    name: Nur-Mecca iOS Automatic Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App (Try Automatic Twice)
        script: |
          # Define the Archive command
          ARCHIVE_CMD="xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release -archivePath build/ios/xcarchive/App.xcarchive archive"
          
          echo "🚀 ATTEMPT 1: Starting Automatic Archive..."
          if $ARCHIVE_CMD; then
            echo "✅ Attempt 1 Succeeded!"
          else
            echo "⚠️ Attempt 1 Failed. Cleaning and retrying..."
            xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
            
            echo "🚀 ATTEMPT 2: Starting Automatic Archive (Retry)..."
            if $ARCHIVE_CMD; then
               echo "✅ Attempt 2 Succeeded!"
            else
               echo "❌ BOTH AUTOMATIC ATTEMPTS FAILED."
               echo "--------------------------------------------------------"
               echo "STEP-BY-STEP MANUAL PREPARATION GUIDE:"
               echo "1. Log into developer.apple.com"
               echo "2. Go to 'Certificates, Identifiers & Profiles'"
               echo "3. Find your 'App Store' Provisioning Profile for $BUNDLE_ID"
               echo "4. Copy the 'UUID' (e.g. 12345-ABCDE-6789...)"
               echo "5. Note your 10-character 'Team ID'"
               echo "6. Paste these into the Manual YAML I previously provided."
               echo "--------------------------------------------------------"
               exit 65
            fi
          fi

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa