workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build || echo "No build script, using static files"

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive archive

    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive
