workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Fix API Key and Signing
        script: |
          # 1. Clean and Save API Key (Handles both Base64 and Raw Text)
          # This python script removes any accidental spaces/newlines from the secret
          python3 - <<EOF
          import os, base64
          raw_key = os.environ.get('APP_STORE_CONNECT_PRIVATE_KEY', '').strip()
          with open('/tmp/Apple_API_Key.p8', 'w') as f:
              if "-----BEGIN" in raw_key:
                  f.write(raw_key)
              else:
                  # Try decoding if it looks like base64
                  try:
                      decoded = base64.b64decode(raw_key).decode('utf-8')
                      f.write(decoded)
                  except:
                      f.write(raw_key)
          EOF
          chmod 600 /tmp/Apple_API_Key.p8
          
          # 2. Fetch Profiles
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 3. Identify Profile
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}" | head -n 1)
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 4. Create ExportOptions.plist
          cat <<EOF > /tmp/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROV_PROFILE_UUID</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF
      - name: Build iOS App
        script: |
          # Verify key exists before building
          if [ ! -f /tmp/Apple_API_Key.p8 ]; then echo "Error: API Key file missing"; exit 1; fi
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "/tmp/Apple_API_Key.p8" \
            -exportOptionsPlist /tmp/exportOptions.plist \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
    artifacts:
      - build/ios/xcarchive/*.xcarchive