workflows:
  ios-workflow:
    name: Nur-Mecca iOS Manual Build
    max_build_duration: 60
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Set up code signing
        script: |
          # Use Codemagic's built-in command to prepare the manual files you just uploaded
          keychain initialize
          # This will automatically pick up the .p12 and .mobileprovision you uploaded to the UI
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            clean archive
    artifacts:
      - build/ios/xcarchive/*.xcarchive