workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: |
          npx cap sync ios
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
      
      - name: Build and Sign iOS App
        script: |
          # 1. Setup API Key
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8

          # 2. Fetch Signing Files
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          
          # 3. Detect Profile
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}" | head -n 1)
          PROV_PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print :Name" /dev/stdin <<< $(security cms -D -i "$PROV_PROFILE_PATH"))
          
          echo "Using Profile: $PROV_PROFILE_NAME ($PROV_PROFILE_UUID)"

          # 4. Create ExportOptions.plist
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROV_PROFILE_NAME</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF

          # 5. ADVANCED RECURSIVE PATCHING (Targets TargetAttributes + BuildSettings)
          python3 -c "
          import sys, re, os
          uuid, name, team = '$PROV_PROFILE_UUID', '$PROV_PROFILE_NAME', '$DEVELOPMENT_TEAM'
          
          for root, dirs, files in os.walk('.'):
              for file in files:
                  if file == 'project.pbxproj':
                      path = os.path.join(root, file)
                      with open(path, 'r') as f: content = f.read()

                      # Fix A: Force Manual Signing in TargetAttributes (The UI Toggle)
                      content = re.sub(r'ProvisioningStyle = [A-Za-z]+;', 'ProvisioningStyle = Manual;', content)
                      
                      # Fix B: Global Team ID
                      content = re.sub(r'DevelopmentTeam = [A-Z0-9]+;', f'DevelopmentTeam = {team};', content)

                      # Fix C: Force Profile UUID and Specifier into Build Settings
                      # We wipe existing ones first to prevent duplicates
                      content = re.sub(r'PROVISIONING_PROFILE = \"[^\"]*\";', '', content)
                      content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = \"[^\"]*\";', '', content)
                      
                      settings_to_add = [
                          f'PROVISIONING_PROFILE = \"{uuid}\";',
                          f'PROVISIONING_PROFILE_SPECIFIER = \"{name}\";',
                          f'DEVELOPMENT_TEAM = {team};',
                          'CODE_SIGN_STYLE = Manual;',
                          'CODE_SIGN_IDENTITY = \"Apple Distribution\";',
                          '\"CODE_SIGN_IDENTITY[sdk=iphoneos*]\" = \"Apple Distribution\";',
                          'AD_HOC_CODE_SIGNING_ALLOWED = YES;'
                      ]
                      
                      pattern = r'(buildSettings = \{)'
                      replacement = r'\1\n\t\t\t\t' + '\n\t\t\t\t'.join(settings_to_add)
                      content = re.sub(pattern, replacement, content)

                      with open(path, 'w') as f: f.write(content)
          "

          # 6. ARCHIVE with strict path creation and target overrides
          mkdir -p build/ios/xcarchive
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$ISSUER_ID" \
            -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8 \
            -allowProvisioningUpdates \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_NAME" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive | tee xcodebuild_archive.log

          # 7. EXPORT (Check if archive exists first to provide better error logging)
          if [ ! -d "build/ios/xcarchive/App.xcarchive" ]; then
             echo "Error: Archive failed to generate. Check xcodebuild_archive.log"
             exit 1
          fi

          xcodebuild \
            -exportArchive \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$ISSUER_ID" \
            -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8

      - name: Sync Back to Repository
        script: |
          git config --global user.email "builder@codemagic.io"
          git config --global user.name "Codemagic Builder"
          find . -name "project.pbxproj" -exec git add {} +
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "fix: explicit archive path and target signing overrides"
            git push origin HEAD:main
          else
            echo "No changes to sync."
          fi

    publishing:
      app_store_connect:
        auth: integration
    artifacts:
      - build/ios/xcarchive/*.xcarchive
      - build/ios/ipa/*.ipa