# PROJECT NUR-MECCA | Manual Final Hardcoded Build
workflows:
  ios-production:
    name: Nur-Mecca iOS Manual Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        # ----------------------------------------------------------------
        # 1. PASTE YOUR 10-CHARACTER TEAM ID HERE
        MANUAL_TEAM_ID: "ZQ995AD296"
        # 2. PASTE YOUR PROFILE UUID HERE
        MANUAL_PROFILE_UUID: "eba2ce03-c54a-447a-b1a5-d97006c92fe0"
        # ----------------------------------------------------------------
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          
          # Manually decode and add the P12 certificate from Environment Variables
          echo $CERTIFICATE_BASE64 | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CERTIFICATE_PASSWORD
          
          # Fetch the profile (this handles the .mobileprovision file)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Confirm the certificate is now visible in the keychain
          security find-identity -v -p codesigning
      - name: Build iOS App (Manual Override)
        script: |
          PBXPROJ="$XCODE_PROJECT/project.pbxproj"
          
          echo "🛠️ Forcing Project File to Manual Signing..."
          # Set Manual Mode
          sed -i '' "s/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g" "$PBXPROJ"
          # Inject Team ID
          sed -i '' "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = $MANUAL_TEAM_ID;/g" "$PBXPROJ"
          # Inject Profile UUID
          sed -i '' "s/PROVISIONING_PROFILE = .*/PROVISIONING_PROFILE = \"$MANUAL_PROFILE_UUID\";/g" "$PBXPROJ"
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = \"$MANUAL_PROFILE_UUID\";/g" "$PBXPROJ"

          # Create the required ExportOptions.plist
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$MANUAL_PROFILE_UUID</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>$MANUAL_TEAM_ID</string>
          </dict>
          </plist>
          EOF

          echo "🚀 Starting Archive..."
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$MANUAL_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$MANUAL_PROFILE_UUID" \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa