# PROJECT NUR-MECCA | Force Profile Matching Config
workflows:
  ios-production:
    name: Nur-Mecca iOS Team Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          # We use the --ignore-signing flag which allows the archive to complete
          # without a profile, then the tool applies the signing during export.
          xcode-project build-ipa \
            --project="$XCODE_PROJECT" \
            --scheme="$XCODE_SCHEME" \
            --ignore-signing \
            --export-flags="-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log