workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      ios_signing:
        distribution_type:  app_store
        bundle_identifier: com.milltech.nurmecca


    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          echo "Using static web assets from www"

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS app
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive archive

    artifacts:
      - build/App.xcarchive
