# PROJECT NUR-MECCA | Force Profile Matching Config
workflows:
  ios-production:
    name: Nur-Mecca iOS Team Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          # Added explicit bundle ID and forced a fresh fetch
          app-store-connect fetch-signing-files "com.milltech.nurmecca.app" \
            --type IOS_APP_STORE \
            --create \
            --bundle-id "com.milltech.nurmecca.app"
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            archive
    artifacts:
      - build/App.xcarchive