workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Hard-Reset Project Signing
        script: |
          # 1. API KEY SETUP
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/Apple_API_Key.p8
          export AUTH_KEY_PATH=/tmp/Apple_API_Key.p8

          # 2. INITIALIZE KEYCHAIN & FETCH
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 3. EXTRACT PROFILE UUID
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}")
          echo "Found Profile UUID: $PROV_PROFILE_UUID"
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 4. SURGICAL PROJECT REPAIR
          python3 - <<EOF
          import os
          import re

          def surgical_patch(file_path, uuid, team_id):
              if not os.path.exists(file_path):
                  return
              
              with open(file_path, 'r') as f:
                  lines = f.readlines()

              new_lines = []
              for line in lines:
                  # Force Manual Style
                  line = line.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
                  
                  # Inject Team ID
                  if 'DevelopmentTeam =' in line:
                      line = re.sub(r'DevelopmentTeam = [A-Z0-9]*;', f'DevelopmentTeam = {team_id};', line)
                  
                  # Inject Profile UUID
                  if 'PROVISIONING_PROFILE_SPECIFIER =' in line:
                      line = f'\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "{uuid}";\n'
                  if 'PROVISIONING_PROFILE =' in line:
                      line = f'\t\t\t\tPROVISIONING_PROFILE = "{uuid}";\n'
                      
                  new_lines.append(line)

              with open(file_path, 'w') as f:
                  f.writelines(new_lines)
              print(f"Surgically patched {file_path}")

          surgical_patch('ios/App/App.xcodeproj/project.pbxproj', '$PROV_PROFILE_UUID', '$DEVELOPMENT_TEAM')
          EOF
      - name: Build iOS App
        script: |
          # Explicitly pass the UUID to the build command
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    artifacts:
      - build/ios/xcarchive/*.xcarchive