workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Hard-Reset Project Signing
        script: |
          # 1. API KEY SETUP
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/Apple_API_Key.p8
          export AUTH_KEY_PATH=/tmp/Apple_API_Key.p8

          # 2. INITIALIZE KEYCHAIN & FETCH
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 3. EXTRACT PROFILE UUID
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}")
          echo "Found Profile UUID: $PROV_PROFILE_UUID"
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 4. NUCLEAR TARGET ATTRIBUTE REWRITE
          # This script targets the TargetAttributes block where Xcode stores the GUI checkbox state
          python3 - <<EOF
          import os
          import re

          def nuclear_patch(file_path, uuid, team_id):
              with open(file_path, 'r') as f:
                  content = f.read()

              # Force Manual Style in every build configuration
              content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
              
              # Replace any existing profile refs with the one we just downloaded
              content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = ".*?";', f'PROVISIONING_PROFILE_SPECIFIER = "{uuid}";', content)
              content = re.sub(r'PROVISIONING_PROFILE = ".*?";', f'PROVISIONING_PROFILE = "{uuid}";', content)
              content = re.sub(r'DevelopmentTeam = [A-Z0-9]*;', f'DevelopmentTeam = {team_id};', content)

              # Patch the TargetAttributes section which often overrides the build settings
              # This finds the attributes for each target and injects the manual style
              if 'TargetAttributes = {' in content:
                  # This regex looks for target blocks inside TargetAttributes and ensures they are set to Manual
                  pattern = r'([A-Z0-9]{24} = \{)([^}]*)'
                  replacement = r'\1\2\n\t\t\t\t\t\t\t\tProvisioningStyle = Manual;\n\t\t\t\t\t\t\t\tDevelopmentTeam = {team_id};'
                  content = re.sub(pattern, replacement, content)

              with open(file_path, 'w') as f:
                  f.write(content)
              print(f"Patched {file_path}")

          target = 'ios/App/App.xcodeproj/project.pbxproj'
          if os.path.exists(target):
              nuclear_patch(target, '$PROV_PROFILE_UUID', '$DEVELOPMENT_TEAM')
          EOF
      - name: Build iOS App
        script: |
          # Use explicit signing flags in xcodebuild to override any remaining cached profiles
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    artifacts:
      - build/ios/xcarchive/*.xcarchive