workflows:
  ios-workflow:
    name: Nur-Mecca iOS Manual Build
    max_build_duration: 60
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC" 
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Set up code signing
        script: |
          # 1. Initialize the keychain
          keychain initialize
          
          # 2. Add certificates from the Codemagic Global Keystore
          keychain add-certificates --global-keystore
          
          # 3. Import profiles and extract the UUID for the build
          xcode-project use-profiles
          
          # 4. Find the UUID of the profile we just imported to use in the build command
          PROVISIONING_PROFILE_UUID=$(mobile-static find-profile-uuid --bundle-id "$BUNDLE_ID")
          echo "export PROVISIONING_PROFILE_UUID=$PROVISIONING_PROFILE_UUID" >> $CM_ENV
      - name: Build iOS App
        script: |
          # Passing the UUID explicitly to fix the "Requires a provisioning profile" error
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_UUID" \
            CODE_SIGN_STYLE=Manual \
            clean archive
    artifacts:
      - build/ios/xcarchive/*.xcarchive