workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Hard-Reset Project Signing
        script: |
          # 1. Setup API Key
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/Apple_API_Key.p8
          export AUTH_KEY_PATH=/tmp/Apple_API_Key.p8

          # 2. Fetch and Install Profiles
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 3. Get the Profile UUID accurately
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}" | head -n 1)
          echo "Using Profile UUID: $PROV_PROFILE_UUID"
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 4. Reinforced metadata fix for Xcode 16+
          python3 - <<EOF
          import os
          import re

          path = 'ios/App/App.xcodeproj/project.pbxproj'
          uuid = os.environ.get("PROV_PROFILE_UUID")
          team = os.environ.get("DEVELOPMENT_TEAM")

          if os.path.exists(path):
              with open(path, 'r') as f:
                  content = f.read()
              
              # Force Manual Provisioning Style everywhere
              content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
              
              # Targeted Regex replacement for build settings to ensure they are set correctly
              content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {team};', content)
              content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = [^;]+;', f'PROVISIONING_PROFILE_SPECIFIER = "{uuid}";', content)
              content = re.sub(r'PROVISIONING_PROFILE = [^;]+;', f'PROVISIONING_PROFILE = "{uuid}";', content)
              content = re.sub(r'CODE_SIGN_STYLE = [^;]+;', 'CODE_SIGN_STYLE = Manual;', content)
              content = re.sub(r'CODE_SIGN_IDENTITY = [^;]+;', 'CODE_SIGN_IDENTITY = "Apple Distribution";', content)

              # Special fix for TargetAttributes block which often causes the 'Select a profile' error
              # This ensures the attribute 'provisioningCertificateSpecifier' matches our profile
              content = re.sub(r'provisioningCertificateSpecifier = [^;]+;', f'provisioningCertificateSpecifier = "Apple Distribution";', content)

              with open(path, 'w') as f:
                  f.write(content)
              print("Xcode project file reinforced and updated.")
          EOF
      - name: Build iOS App
        script: |
          # Passing explicit settings to xcodebuild as the final override
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            -allowProvisioningUpdates \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    artifacts:
      - build/ios/xcarchive/*.xcarchive