# PROJECT NUR-MECCA | Managed Signing for Windows Users
workflows:
  ios-production:
    name: Nur-Mecca iOS Managed Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        # ----------------------------------------------------------------
        # Your Team ID is visible in the Membership section of developer.apple.com
        MANUAL_TEAM_ID: "U2SA5VYGH7"
        # ----------------------------------------------------------------
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          
          # This command is the 'Magic' for Windows users. 
          # It uses your API Key to create a Certificate and Profile automatically 
          # if they don't exist, and installs them into the build machine.
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          keychain add-certificates
          
          # This tells the Xcode project to use the profiles we just fetched
          xcode-project use-profiles
      - name: Build iOS App (Managed Build)
        script: |
          # Create the required ExportOptions.plist automatically
          # We use 'automatic' style here because Codemagic is managing the profile
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>$MANUAL_TEAM_ID</string>
          </dict>
          </plist>
          EOF

          echo "🚀 Starting Archive..."
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            clean archive \
            DEVELOPMENT_TEAM="$MANUAL_TEAM_ID"

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa