scripts:
  - name: Install dependencies
    script: |
      npm install

  - name: Build web assets
    script: |
      echo "Using static web assets from www"

  - name: Sync Capacitor
    script: |
      npx cap sync ios

  - name: Set up code signing
    script: |
      keychain initialize
      app-store-connect fetch-signing-files com.milltech.nurmecca.app --type IOS_APP_STORE
      keychain add-certificates
      xcode-project use-profiles

  - name: Build iOS app
    script: |
      xcodebuild \
        -project ios/App/App.xcodeproj \
        -scheme App \
        -configuration Release \
        -sdk iphoneos \
        -archivePath build/App.xcarchive \
        -allowProvisioningUpdates \
        archive
