workflows:
  ios-capacitor:
    name: iOS Capacitor Build (Nur-Mecca)
    max_build_duration: 60

    environment:
      node: 22
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          echo "Static site – skipping build"

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive archive

    artifacts:
      - build/**/*.xcarchive
