workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    integrations:
      app_store_connect: "Codemagic_Key"
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Hard-Reset Project Signing
        script: |
          # 1. Setup API Key
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/Apple_API_Key.p8
          export AUTH_KEY_PATH=/tmp/Apple_API_Key.p8

          # 2. Fetch and Install Profiles
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # 3. Get the Profile UUID accurately
          PROV_PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}" | head -n 1)
          echo "Using Profile UUID: $PROV_PROFILE_UUID"
          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV

          # 4. Surgical metadata fix for Xcode 16+
          python3 - <<EOF
          import os
          import re

          path = 'ios/App/App.xcodeproj/project.pbxproj'
          if os.path.exists(path):
              with open(path, 'r') as f:
                  lines = f.readlines()
              
              fixed_lines = []
              for line in lines:
                  # Force Manual Style
                  line = line.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
                  
                  # Inject variables into build settings blocks
                  if 'DEVELOPMENT_TEAM =' in line:
                      line = f'\t\t\t\tDEVELOPMENT_TEAM = {os.environ.get("DEVELOPMENT_TEAM")};\n'
                  if 'PROVISIONING_PROFILE_SPECIFIER =' in line:
                      line = f'\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "{os.environ.get("PROV_PROFILE_UUID")}";\n'
                  if 'PROVISIONING_PROFILE =' in line:
                      line = f'\t\t\t\tPROVISIONING_PROFILE = "{os.environ.get("PROV_PROFILE_UUID")}";\n'
                  if 'CODE_SIGN_STYLE =' in line:
                      line = '\t\t\t\tCODE_SIGN_STYLE = Manual;\n'
                  if 'CODE_SIGN_IDENTITY =' in line:
                      line = '\t\t\t\tCODE_SIGN_IDENTITY = "Apple Distribution";\n'
                  
                  fixed_lines.append(line)
              
              with open(path, 'w') as f:
                  f.writelines(fixed_lines)
              print("Xcode project file surgically updated.")
          EOF
      - name: Build iOS App
        script: |
          # Use the explicit UUID to bypass Xcode's internal profile search logic
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            clean archive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    artifacts:
      - build/ios/xcarchive/*.xcarchive