# PROJECT NUR-MECCA | Force Profile Matching Config
workflows:
  ios-production:
    name: Nur-Mecca iOS Team Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          # 1. Extract verified metadata from the downloaded profile
          PROV_PROFILE_PATH=$(ls "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision | head -n 1)
          PROV_PROFILE_UUID=$(grep -aA1 "UUID" "$PROV_PROFILE_PATH" | grep -oE "[-A-Z0-9]{36}")
          # Extract Team ID directly from the profile
          PROFILE_TEAM_ID=$(grep -aA1 "ApplicationIdentifierPrefix" "$PROV_PROFILE_PATH" | grep -oE "[A-Z0-9]{10}" | head -n 1)
          
          echo "Using Profile UUID: $PROV_PROFILE_UUID"
          echo "Detected Team ID: $PROFILE_TEAM_ID"

          # 2. ULTRA-AGGRESSIVE PROJECT PATCHING
          PBXPROJ="$XCODE_PROJECT/project.pbxproj"
          
          # Force Manual signing and set IDs globally in the project file
          sed -i '' "s/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g" "$PBXPROJ"
          sed -i '' "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = $PROFILE_TEAM_ID;/g" "$PBXPROJ"
          sed -i '' "s/PROVISIONING_PROFILE = .*/PROVISIONING_PROFILE = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"
          
          # 3. Generate ExportOptions.plist
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROV_PROFILE_UUID</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>$PROFILE_TEAM_ID</string>
          </dict>
          </plist>
          EOF

          # 4. Native Archive with Clean and Extra Flags
          # 'clean' ensures we aren't using broken cached settings
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$PROFILE_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            ALLOW_PROVISIONING_DEVICE_REGISTRATION=YES

          # 5. Export IPA
          xcodebuild \
            -exportArchive \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log