# PROJECT NUR-MECCA | Force Profile Matching Config
workflows:
  ios-production:
    name: Nur-Mecca iOS Team Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure Signing & Profiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          # 1. Manually find the Profile Name from the Codemagic environment
          PROV_PROFILE=$(ls "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision | xargs basename -s .mobileprovision | head -n 1)
          echo "Using Profile: $PROV_PROFILE"

          # 2. Generate ExportOptions.plist with explicit values
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROV_PROFILE</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

          # 3. Native Archive (bypassing Codemagic wrapper to avoid Status 70)
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_DESIRED=NO

          # 4. Export IPA using the generated Plist
          xcodebuild \
            -exportArchive \
            -archivePath "build/ios/xcarchive/App.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log