workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Force Node 22
        script: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
          node -v
          npm -v

      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive archive

    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
