workflows:
  ios-workflow:
    name: Nur-Mecca iOS Automatic Build
    max_build_duration: 60
    environment:
      groups:
        - apple_auth 
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.milltech.nurmecca.app"
        DEVELOPMENT_TEAM: "JBMD9M6ZPC"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "U2SA5VYGH7"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Prepare Signing
        script: |
          # 1. Set Git Identity
          git config --global user.email "builder@codemagic.io"
          git config --global user.name "Codemagic Builder"

          # 2. Create the .p8 key file
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/Apple_API_Key.p8
          echo "export AUTH_KEY_PATH=/tmp/Apple_API_Key.p8" >> $CM_ENV

          # 3. Fetch signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          xcode-project use-profiles

          # 4. NUCLEAR PBXPROJ PATCHING
          # Find the downloaded profile UUID
          PROV_PROFILE_UUID=$(ls -t ~/Library/MobileDevice/Provisioning\ Profiles | head -n 1 | cut -d. -f1)
          echo "Targeting Profile UUID: $PROV_PROFILE_UUID"
          
          PBXPROJ="$XCODE_PROJECT/project.pbxproj"
          
          # Force ProvisioningStyle to Manual for all targets
          sed -i '' 's/ProvisioningStyle = [A-Za-z]*;/ProvisioningStyle = Manual;/g' "$PBXPROJ"
          
          # Force the Team ID everywhere
          sed -i '' "s/DevelopmentTeam = [A-Z0-9]*;/DevelopmentTeam = $DEVELOPMENT_TEAM;/g" "$PBXPROJ"
          
          # Force the Profile UUID into every possible variant of the profile key
          sed -i '' "s/PROVISIONING_PROFILE = \".*\";/PROVISIONING_PROFILE = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = \".*\";/PROVISIONING_PROFILE_SPECIFIER = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"
          sed -i '' "s/\"PROVISIONING_PROFILE\[sdk=iphoneos\*\]\" = \".*\";/\"PROVISIONING_PROFILE\[sdk=iphoneos\*\]\" = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"
          sed -i '' "s/\"PROVISIONING_PROFILE_SPECIFIER\[sdk=iphoneos\*\]\" = \".*\";/\"PROVISIONING_PROFILE_SPECIFIER\[sdk=iphoneos\*\]\" = \"$PROV_PROFILE_UUID\";/g" "$PBXPROJ"

          echo "export PROV_PROFILE_UUID=$PROV_PROFILE_UUID" >> $CM_ENV
      - name: Build iOS App
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PROVISIONING_PROFILE="$PROV_PROFILE_UUID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROV_PROFILE_UUID" \
            CODE_SIGN_STYLE=Manual \
            clean archive
    artifacts:
      - build/ios/xcarchive/*.xcarchive